#Raw document of results for initial table and code used to generate it (R/4.2.0)
library(data.table)
PGS_Catalog_Associations <- fread("/sc/arion/projects/igh/data/pgs_catalog/superpop_scores_103024/scores/ALL_aggregated_scores.txt.gz")
colnames(PGS_Catalog_Associations)
nrow(PGS_Catalog_Associations[which(PGS_Catalog_Associations$Age < 20),])
nrow(PGS_Catalog_Associations[which(PGS_Catalog_Associations$Age < 30 & PGS_Catalog_Associations$Age > 20),])
nrow(PGS_Catalog_Associations[which(PGS_Catalog_Associations$Age < 40 & PGS_Catalog_Associations$Age > 30),])
nrow(PGS_Catalog_Associations[which(PGS_Catalog_Associations$Age < 50 & PGS_Catalog_Associations$Age > 40),])
nrow(PGS_Catalog_Associations[which(PGS_Catalog_Associations$Age < 60 & PGS_Catalog_Associations$Age > 50),])
nrow(PGS_Catalog_Associations[which(PGS_Catalog_Associations$Age < 70 & PGS_Catalog_Associations$Age > 60),])
nrow(PGS_Catalog_Associations[which(PGS_Catalog_Associations$Age < 80 & PGS_Catalog_Associations$Age > 70),])
nrow(PGS_Catalog_Associations[which(PGS_Catalog_Associations$Age < 90 & PGS_Catalog_Associations$Age > 80),])
nrow(PGS_Catalog_Associations[which(PGS_Catalog_Associations$Age < 100 & PGS_Catalog_Associations$Age > 90),])
nrow(PGS_Catalog_Associations[which(PGS_Catalog_Associations$Age < 110 & PGS_Catalog_Associations$Age > 100),])
nrow(PGS_Catalog_Associations[which(PGS_Catalog_Associations$Age < 120 & PGS_Catalog_Associations$Age > 110),])
nrow(PGS_Catalog_Associations[which(PGS_Catalog_Associations$Age < 20),])
table(as.factor(PGS_Catalog_Associations$SequencedGender))
table(as.factor(PGS_Catalog_Associations$Ancestry))
AFR_PGS_Catalog <- PGS_Catalog_Associations[which(PGS_Catalog_Associations$Ancestry == "AFR"),]
AMR_PGS_Catalog <- PGS_Catalog_Associations[which(PGS_Catalog_Associations$Ancestry == "AMR"),]
EUR_PGS_Catalog <- PGS_Catalog_Associations[which(PGS_Catalog_Associations$Ancestry == "EUR"),]
EAS_PGS_Catalog <- PGS_Catalog_Associations[which(PGS_Catalog_Associations$Ancestry == "EAS"),]
SAS_PGS_Catalog <- PGS_Catalog_Associations[which(PGS_Catalog_Associations$Ancestry == "SAS"),]
table(as.factor(AFR_PGS_Catalog$SequencedGender))
table(as.factor(AMR_PGS_Catalog$SequencedGender))
table(as.factor(EUR_PGS_Catalog$SequencedGender))
table(as.factor(EAS_PGS_Catalog$SequencedGender))
table(as.factor(SAS_PGS_Catalog$SequencedGender))
nrow(AFR_PGS_Catalog[which(AFR_PGS_Catalog$Age < 20),])
nrow(AFR_PGS_Catalog[which(AFR_PGS_Catalog$Age < 30 & AFR_PGS_Catalog$Age > 20),])
nrow(AFR_PGS_Catalog[which(AFR_PGS_Catalog$Age < 40 & AFR_PGS_Catalog$Age > 30),])
nrow(AFR_PGS_Catalog[which(AFR_PGS_Catalog$Age < 50 & AFR_PGS_Catalog$Age > 40),])
nrow(AFR_PGS_Catalog[which(AFR_PGS_Catalog$Age < 60 & AFR_PGS_Catalog$Age > 50),])
nrow(AFR_PGS_Catalog[which(AFR_PGS_Catalog$Age < 70 & AFR_PGS_Catalog$Age > 60),])
nrow(AFR_PGS_Catalog[which(AFR_PGS_Catalog$Age < 80 & AFR_PGS_Catalog$Age > 70),])
nrow(AFR_PGS_Catalog[which(AFR_PGS_Catalog$Age < 90 & AFR_PGS_Catalog$Age > 80),])
nrow(AFR_PGS_Catalog[which(AFR_PGS_Catalog$Age < 100 & AFR_PGS_Catalog$Age > 90),])
nrow(AFR_PGS_Catalog[which(AFR_PGS_Catalog$Age < 110 & AFR_PGS_Catalog$Age > 100),])
nrow(AFR_PGS_Catalog[which(AFR_PGS_Catalog$Age < 120 & AFR_PGS_Catalog$Age > 110),])
nrow(AMR_PGS_Catalog[which(AMR_PGS_Catalog$Age < 20),])
nrow(AMR_PGS_Catalog[which(AMR_PGS_Catalog$Age < 30 & AMR_PGS_Catalog$Age > 20),])
nrow(AMR_PGS_Catalog[which(AMR_PGS_Catalog$Age < 40 & AMR_PGS_Catalog$Age > 30),])
nrow(AMR_PGS_Catalog[which(AMR_PGS_Catalog$Age < 50 & AMR_PGS_Catalog$Age > 40),])
nrow(AMR_PGS_Catalog[which(AMR_PGS_Catalog$Age < 60 & AMR_PGS_Catalog$Age > 50),])
nrow(AMR_PGS_Catalog[which(AMR_PGS_Catalog$Age < 70 & AMR_PGS_Catalog$Age > 60),])
nrow(AMR_PGS_Catalog[which(AMR_PGS_Catalog$Age < 80 & AMR_PGS_Catalog$Age > 70),])
nrow(AMR_PGS_Catalog[which(AMR_PGS_Catalog$Age < 90 & AMR_PGS_Catalog$Age > 80),])
nrow(AMR_PGS_Catalog[which(AMR_PGS_Catalog$Age < 100 & AMR_PGS_Catalog$Age > 90),])
nrow(AMR_PGS_Catalog[which(AMR_PGS_Catalog$Age < 110 & AMR_PGS_Catalog$Age > 100),])
nrow(AMR_PGS_Catalog[which(AMR_PGS_Catalog$Age < 120 & AMR_PGS_Catalog$Age > 110),])
nrow(EUR_PGS_Catalog[which(EUR_PGS_Catalog$Age < 20),])
nrow(EUR_PGS_Catalog[which(EUR_PGS_Catalog$Age < 30 & EUR_PGS_Catalog$Age > 20),])
nrow(EUR_PGS_Catalog[which(EUR_PGS_Catalog$Age < 40 & EUR_PGS_Catalog$Age > 30),])
nrow(EUR_PGS_Catalog[which(EUR_PGS_Catalog$Age < 50 & EUR_PGS_Catalog$Age > 40),])
nrow(EUR_PGS_Catalog[which(EUR_PGS_Catalog$Age < 60 & EUR_PGS_Catalog$Age > 50),])
nrow(EUR_PGS_Catalog[which(EUR_PGS_Catalog$Age < 70 & EUR_PGS_Catalog$Age > 60),])
nrow(EUR_PGS_Catalog[which(EUR_PGS_Catalog$Age < 80 & EUR_PGS_Catalog$Age > 70),])
nrow(EUR_PGS_Catalog[which(EUR_PGS_Catalog$Age < 90 & EUR_PGS_Catalog$Age > 80),])
nrow(EUR_PGS_Catalog[which(EUR_PGS_Catalog$Age < 100 & EUR_PGS_Catalog$Age > 90),])
nrow(EUR_PGS_Catalog[which(EUR_PGS_Catalog$Age < 110 & EUR_PGS_Catalog$Age > 100),])
nrow(EUR_PGS_Catalog[which(EUR_PGS_Catalog$Age < 120 & EUR_PGS_Catalog$Age > 110),])
nrow(EAS_PGS_Catalog[which(EAS_PGS_Catalog$Age < 20),])
nrow(EAS_PGS_Catalog[which(EAS_PGS_Catalog$Age < 30 & EAS_PGS_Catalog$Age > 20),])
nrow(EAS_PGS_Catalog[which(EAS_PGS_Catalog$Age < 40 & EAS_PGS_Catalog$Age > 30),])
nrow(EAS_PGS_Catalog[which(EAS_PGS_Catalog$Age < 50 & EAS_PGS_Catalog$Age > 40),])
nrow(EAS_PGS_Catalog[which(EAS_PGS_Catalog$Age < 60 & EAS_PGS_Catalog$Age > 50),])
nrow(EAS_PGS_Catalog[which(EAS_PGS_Catalog$Age < 70 & EAS_PGS_Catalog$Age > 60),])
nrow(EAS_PGS_Catalog[which(EAS_PGS_Catalog$Age < 80 & EAS_PGS_Catalog$Age > 70),])
nrow(EAS_PGS_Catalog[which(EAS_PGS_Catalog$Age < 90 & EAS_PGS_Catalog$Age > 80),])
nrow(EAS_PGS_Catalog[which(EAS_PGS_Catalog$Age < 100 & EAS_PGS_Catalog$Age > 90),])
nrow(EAS_PGS_Catalog[which(EAS_PGS_Catalog$Age < 110 & EAS_PGS_Catalog$Age > 100),])
nrow(EAS_PGS_Catalog[which(EAS_PGS_Catalog$Age < 120 & EAS_PGS_Catalog$Age > 110),])
nrow(SAS_PGS_Catalog[which(SAS_PGS_Catalog$Age < 20),])
nrow(SAS_PGS_Catalog[which(SAS_PGS_Catalog$Age < 30 & SAS_PGS_Catalog$Age > 20),])
nrow(SAS_PGS_Catalog[which(SAS_PGS_Catalog$Age < 40 & SAS_PGS_Catalog$Age > 30),])
nrow(SAS_PGS_Catalog[which(SAS_PGS_Catalog$Age < 50 & SAS_PGS_Catalog$Age > 40),])
nrow(SAS_PGS_Catalog[which(SAS_PGS_Catalog$Age < 60 & SAS_PGS_Catalog$Age > 50),])
nrow(SAS_PGS_Catalog[which(SAS_PGS_Catalog$Age < 70 & SAS_PGS_Catalog$Age > 60),])
nrow(SAS_PGS_Catalog[which(SAS_PGS_Catalog$Age < 80 & SAS_PGS_Catalog$Age > 70),])
nrow(SAS_PGS_Catalog[which(SAS_PGS_Catalog$Age < 90 & SAS_PGS_Catalog$Age > 80),])
nrow(SAS_PGS_Catalog[which(SAS_PGS_Catalog$Age < 100 & SAS_PGS_Catalog$Age > 90),])
nrow(SAS_PGS_Catalog[which(SAS_PGS_Catalog$Age < 110 & SAS_PGS_Catalog$Age > 100),])
q()
